= The Music Store

A demo Music Store with Eclipse Vert.x and RxJava

== Runnning

=== The Postgres database

[source,shell]
----
docker run --rm --name musicstore-db -e POSTGRES_USER=music -e POSTGRES_PASSWORD=music -e POSTGRES_DB=musicdb -p 5432:5432 postgres
----

=== The Couchbase server

First start a development server:

[source,shell]
----
docker run --rm --name musicstore-couchbase -p 8091-8093:8091-8093 -p 11210:11210 arungupta/couchbase
----

Then create the album comments bucket:

[source,shell]
----
curl -X POST -u Administrator:password -d name=album-comments -d ramQuotaMB=200 -d authType=none -d proxyPort=11315 http://127.0.0.1:8091/pools/default/buckets
----

=== Development

* Do one time build to pull the dependencies `mvn clean install`
* To run the application in foreground do `mvn vertx:run` with redeploy enabled and uses `io.vertx.core.logging.SLF4JLogDelegateFactory`
* To run the applicaiton in background mode i.e. vertx start do `mvn vertx:start`

Check https://vmp.fabric8.io[fabric8 vertx-maven-plugin] for more information and
examples on using fabric8 vertx-maven-plugin

video::X_G_plK-UG8[youtube]


== Useful stuff

=== Initial dataset

The initial dataset has been created with the `initdb.groovy` script located at the project root.
It parses a https://wiki.gnome.org/Apps/Rhythmbox[Rhythmbox] database file and inserts the data into Postgres.

Then it's easy to create a script for Flyway.

[source,shell]
----
docker exec musicstore-db pg_dump -a --inserts --exclude-table=schema_version -h 127.0.0.1 -U music musicdb > src/main/resources/db/migration/V2__InsertData.sql
----
