= The Music Store

A demo Music Store with Eclipse Vert.x and RxJava

== Runnning

=== The Postgres database

[source,shell]
----
docker run --rm --name musicstore-db -e POSTGRES_USER=music -e POSTGRES_PASSWORD=music -e POSTGRES_DB=musicdb -p 5432:5432 postgres
----

=== The Couchbase server

First start a development server:

[source,shell]
----
docker run --rm --name musicstore-couchbase -p 8091-8093:8091-8093 -p 11210:11210 arungupta/couchbase
----

Then create the album comments bucket:

[source,shell]
----
curl -X POST -u Administrator:password -d name=album-comments -d ramQuotaMB=200 -d authType=none -d proxyPort=11315 http://127.0.0.1:8091/pools/default/buckets
----

=== Development

For fast development turnaround, create a Java application launcher in Eclipse IDE or IntelliJ:

* Main class: `io.vertx.core.Launcher`
* VM options: `-Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory`
* Program arguments: `run io.vertx.demo.musicstore.MusicStoreVerticle --redeploy=target/**/* --launcher-class=io.vertx.core.Launcher`
* Working directory: `</path/to>/vertx-musicstore`


== Useful stuff

=== Updating the event bus client

The event bus client is stored on the VCS, but if you update the Vert.x version property, don't forget to update the event bus client as well:

[source,shell]
----
mvn dependency:copy@copy-eventbus-client
----

=== Initial dataset

The initial dataset has been created with the `initdb.groovy` script located at the project root.
It parses a https://wiki.gnome.org/Apps/Rhythmbox[Rhythmbox] database file and inserts the data into Postgres.

Then it's easy to create a script for Flyway.

[source,shell]
----
docker exec musicstore-db pg_dump -a --inserts --exclude-table=schema_version -h 127.0.0.1 -U music musicdb > src/main/resources/db/migration/V2__InsertData.sql
----
